### ISSUE TITLE
Browser icon difficult to see when tab opend

### ISSUE THREAD

**Issue by phuismann** [yash296/nexd-website#3]
On Chrome the website Icon isnt visible when the tab with nexd is selected. Maybe have our green as the background? 
![image](https://user-images.githubusercontent.com/45405932/79629603-44802300-814b-11ea-912d-13a8ca7b572b.png)

**Comment by yash296** [comment]
@FruitVul  The design team can come up with an Icon (png) for this. I worked with whatever I could find :)

**Comment by qndrey** [comment]
I am on it.

**Comment by qndrey** [comment]
@FruitVul favicon has been updated, we can close this ticket.
